Set up routes with authentication. Reconfigured auth screens and context
PH86/interview pull request #28
Opened 2021-07-06 09:38 UTC by hrjuggins

- Made some changes to the App context so that the context provider and state is handle from within the context file.
- Create a useAppContext hook to access and set this state.

- Did a similar thing for the auth context but this needs further work to be hooked into an api.

- Routes has been moved to a separate file with a new component to handle AuthenticatedRoutes.
- The client side and api urls are contained within the constants.ts file so can be managed in one place.

- Made changes to the sidebar component to handle the new router set up. 
- Created a sidebar link component

2021-07-06 09:41 UTC, PH86 commented on package.json
> +  "homepage": "https://ph86.github.io",
this needs to be /interview or it will clash with my other projects

2021-07-06 09:51 UTC, sambuckley1995 approved these changes

2021-07-06 09:51 UTC, sambuckley1995 commented on src/components/Sidebar/Sidebar.css
> +    /* padding-top: 1rem;
Are these comments still supposed to be here

2021-07-06 09:51 UTC, sambuckley1995 commented on src/components/Sidebar/Sidebar.tsx
> +
I don't think the whitespace is needed here

2021-07-06 09:51 UTC, sambuckley1995 commented on src/index.tsx
> +			<AppContextProvider>
Formatting has gone a little wonky

2021-07-06 09:57 UTC, PH86 requested changes
package.json homepage needs to be https://ph86.github.io/interview and all routes add to this or we will get conflicts with other apps.

2021-07-06 10:31 UTC, PH86 approved these changes

2021-07-06 13:37 UTC, JackHewitt08 requested changes

2021-07-06 13:37 UTC, JackHewitt08 commented on src/App.tsx
> +
remove extra line

2021-07-06 13:37 UTC, JackHewitt08 commented on src/components/Sidebar/Sidebar.css
> +  padding: 1em 2em;
if we use rem everywhere else could we stick to one as rem is more consistent

2021-07-06 13:37 UTC, JackHewitt08 commented on src/components/Sidebar/Sidebar.css
> +  height: 4em;
rem please

2021-07-06 13:37 UTC, JackHewitt08 commented on src/components/Sidebar/Sidebar.css
> +    top: 4em
rem please

2021-07-06 13:37 UTC, JackHewitt08 commented on src/components/Sidebar/components/SidebarLink.tsx
> +
remove extra line

2021-07-06 13:37 UTC, JackHewitt08 commented on src/components/Sidebar/components/SidebarLink.tsx
> +    url: string
add comma here, and add following dangle comma

2021-07-06 13:37 UTC, JackHewitt08 commented on src/components/Sidebar/components/SidebarLink.tsx
> +    const swapOpacity = theme.mode === 'dark'
If we arent using this more than once can we just inline it

2021-07-06 13:37 UTC, JackHewitt08 commented on src/components/VacancyFull/VacancyFull.tsx
> +                        <h1>{jobForm?.jobTitle}</h1>
can we have some error handling behind job form not existing? possibly just conditionally render this whole block  or we're going to get undefined everywhere

2021-07-06 13:37 UTC, JackHewitt08 commented on src/context/AppContext.tsx
> +	jobForm?: {
why is this optional?

2021-07-06 13:37 UTC, JackHewitt08 commented on src/context/AppContext.tsx
> +export {AppContext, AppContextProvider}
new line

2021-07-06 13:37 UTC, JackHewitt08 commented on src/context/AuthContext.tsx
> +        id: number;
export interface IAuthState {
	user?: {
        id: number;
        email: string;
    };
    token?: string
}

2021-07-06 13:37 UTC, JackHewitt08 commented on src/context/AuthContext.tsx
> +export {AuthContext, AuthContextProvider}
new line chief

2021-07-06 13:37 UTC, JackHewitt08 commented on src/context/AuthContext.tsx
> +type IAuthContext = [IAuthState, React.Dispatch<React.SetStateAction<IAuthState>>];
Can this be an object, my eyes don't like this

2021-07-06 13:37 UTC, JackHewitt08 commented on src/hooks/useAppContext.tsx
> +
remove extra line

2021-07-06 13:37 UTC, JackHewitt08 commented on src/hooks/useAppContext.tsx
> +        // setAppState(appState => ({...appState, jobForm: data}))
Could we replace this with a TODO rather than leaving commented code

//TODO Harry- thing your need to do

2021-07-06 13:37 UTC, JackHewitt08 commented on src/hooks/useAuthContext.tsx
> +
remove extra line

2021-07-06 13:37 UTC, JackHewitt08 commented on src/pages/Auth/PasswordReset/PasswordReset.tsx
> +	const [email, setEmail] = useState('')
formatting

2021-07-06 13:37 UTC, JackHewitt08 commented on src/pages/Auth/PasswordReset/PasswordReset.tsx
> +import { url, apiUrl } from 'utils/constants';
double quotes vs single quotes is a battle my eyes will never forget

2021-07-06 13:37 UTC, JackHewitt08 commented on src/pages/Auth/PasswordReset/PasswordReset.tsx
> +	const handleOnChange = (event: React.ChangeEvent<HTMLInputElement>) => {
formatting

2021-07-06 13:37 UTC, JackHewitt08 commented on src/pages/Auth/PasswordReset/PasswordReset.tsx
> +	const handleOnChange = (event: React.ChangeEvent<HTMLInputElement>) => {
Also could we use useCallback here so that we can memoize this, or we will be creating a new instant of handleOnChange every time this component renders

2021-07-06 13:37 UTC, JackHewitt08 commented on src/pages/Auth/PasswordReset/PasswordReset.tsx
> +                res.json()
what are we doing with res.json here?

2021-07-06 13:37 UTC, JackHewitt08 commented on src/pages/Auth/SignIn/SignIn.tsx
> +	const [userDetails, setUserDetails] = useState({email: '', password: ''})
formatting

2021-07-07 10:24 UTC, PH86 approved these changes

2021-07-07 10:38 UTC, JackHewitt08 approved these changes

2021-07-07 11:11 UTC, merged